name: license_review
on:
  pull_request:
    branches:
     - main
    paths:
      - go.mod
      - .github/workflows/license_review.yml
jobs:
  license-check:
    runs-on: ubuntu-latest
    env:
      working-directory: ./tools/license-finder
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
      - name: Install license finder
        run: gem install license_finder
      - name: Run license finder
        run: license_finder
        working-directory: ${{env.working-directory}}